# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindship < Formula
  desc "Orchestrator for AI Coding Agents - Claude Code, Gemini CLI, Codex, OpenCode"
  homepage "https://kindship.ai/cli"
  version "0.1.88"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.88/kindship_0.1.88_darwin_amd64.tar.gz"
      sha256 "fd8c300438f2e229996e511d505eb3fb3adf44f915f2436f97feecf43d33c673"

      define_method(:install) do
        bin.install "kindship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.88/kindship_0.1.88_darwin_arm64.tar.gz"
      sha256 "868a857944068eab17a531eb6aeecf3f43b16a464ae221e2074aceb8cd4e2237"

      define_method(:install) do
        bin.install "kindship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.88/kindship_0.1.88_linux_amd64.tar.gz"
      sha256 "b1ae0f9ea650c2a908a76edc2cd5bf6c12ccd49b6c93919a9e4a8355750e3aad"
      define_method(:install) do
        bin.install "kindship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.88/kindship_0.1.88_linux_arm64.tar.gz"
      sha256 "e794e603c481ced28f52de9ac6d24550aff5da99409d463cdf7ead6bbedbe7ad"
      define_method(:install) do
        bin.install "kindship"
      end
    end
  end

  test do
    system "#{bin}/kindship", "version"
  end
end
