# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindship < Formula
  desc "Orchestrator for AI Coding Agents - Claude Code, Gemini CLI, Codex, OpenCode"
  homepage "https://kindship.ai/cli"
  version "0.1.97"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.97/kindship_0.1.97_darwin_amd64.tar.gz"
      sha256 "b5c9b9f184dc8f249fc22c2e5d8a8abd56e23083970f0e92ac90d457e39c105c"

      define_method(:install) do
        bin.install "kindship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.97/kindship_0.1.97_darwin_arm64.tar.gz"
      sha256 "77e03bae4fc1be4e2ec941a676968f9faa638725e3f41ec723bc28b29ef3c30f"

      define_method(:install) do
        bin.install "kindship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.97/kindship_0.1.97_linux_amd64.tar.gz"
      sha256 "2446522fc2e8bd331897725b6ffe898775c12ccb79c675619688b5e2bc1a3170"
      define_method(:install) do
        bin.install "kindship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindship-ai/kindship-cli/releases/download/v0.1.97/kindship_0.1.97_linux_arm64.tar.gz"
      sha256 "22ebb84b373288051b99722b8a34fbfecb0eaa69e3adcc9954ad2c65d445cd40"
      define_method(:install) do
        bin.install "kindship"
      end
    end
  end

  test do
    system "#{bin}/kindship", "version"
  end
end
